Usgdt002   admin   gérer les véhicules
dta-sherlock/gestion-des-transports-back pull request #2
Opened 2018-06-22 12:51 UTC by valentinlemarie

2018-06-25 07:43 UTC, ValentinBourdaud reviewed
Review ok

2018-06-26 08:04 UTC, rguillome requested changes
Principalement refusée pour la conf de la base de données et les annotations CrossOrigin mal placées

2018-06-26 08:04 UTC, rguillome commented on src/main/java/dev/config/DataSourceMySQLConfig.java
> +        dataSource.setUrl("jdbc:mysql://localhost/gestion_des_transports");
On ne commit pas ses environnements de dev ... C'est pour cela qu'il vaut mieux se prendre un peu plus la tête pour faire une conf. valable une bonne fois pour toute.
La PR doit être un moment où l'on vérifie ce qu'on va pousser dans les étapes supérieures impliquant d'autres collègues dont le travail doit être basé sur un travail de qualité et consciencieux de la part de celui qui fait la PR

2018-06-26 08:04 UTC, rguillome commented on src/main/java/dev/config/SecurityConfig.java
> +        http.authorizeRequests().antMatchers("/**").permitAll().and().csrf().disable();
Mettre un TODO pour activer la protection CSRF par la suite...

2018-06-26 08:04 UTC, rguillome commented on src/main/java/dev/entity/Vehicules.java
> +    String immatriculation;
attention, tu es en Java, mets les visibilités explicites dans tes POJO/Entity...

2018-06-26 08:04 UTC, rguillome commented on src/main/java/dev/repository/VersionRepository.java
> +@CrossOrigin
Idem annotation mal placée

2018-06-26 08:04 UTC, rguillome commented on src/main/java/dev/repository/CarRepository.java
> +public interface CarRepository extends JpaRepository<Vehicules,Integer> {
CrossOrigin sur les Repository? l'idée ce n'est pas d'en coller sur toutes les classes Spring... L'annotation CrossOrigin se place sur les contrôleurs

2018-06-29 07:46 UTC, rguillome approved these changes

2018-06-29 07:46 UTC, rguillome commented on src/main/java/dev/entity/User.java
> +    public User(String email, String password, ROLES roles, boolean IS_ACTIVE, String firstName, String lastName) {
attention au nommage : convention des nommage d'attribut

2018-06-29 07:46 UTC, merged